//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioRentFlat.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costas
    {
        public int Cod_Provincia { get; set; }
        public string NombreProvincia { get; set; }
        public byte[] Foto { get; set; }
    }
}
