//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioRentFlat.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntidadRenting : DbContext
    {
        public EntidadRenting()
            : base("name=EntidadRenting")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Costas> Costas { get; set; }
        public virtual DbSet<Galeria_Fotos> Galeria_Fotos { get; set; }
        public virtual DbSet<Precios_Vivienda> Precios_Vivienda { get; set; }
        public virtual DbSet<Tipos_Vivienda> Tipos_Vivienda { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Viviendas> Viviendas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
