//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioRentFlat.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galeria_Fotos
    {
        public int Cod_imagen { get; set; }
        public int Cod_casa { get; set; }
        public byte[] Foto { get; set; }
        public int Orden { get; set; }
    }
}
