//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioRentFlat.Context
{
    using System;
    using System.Collections.Generic;
    using System.Security.Principal;

    public partial class Usuarios: IPrincipal
    {
        public int Cod_usuario { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int DIR { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public bool Mostrar_info_contacto { get; set; }
        public string Perfil { get; set; }
        public Usuarios(IIdentity identidad)
        {
            this.Identity = identidad;
        }
        public Usuarios() { }
        public bool IsInRole(string role)
        {
            if (this.Perfil.ToUpper() == role.ToUpper())
            {
                return true;
            }
            else
            {
                return false;
            }
            //foreach (String r in this.Roles)
            //{
            //    if (r.ToUpper() == role.ToUpper())
            //    {
            //        return true;
            //    }
            //}
            //return false;
        }
        public IIdentity Identity { get; set; }
    }
}

