//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioRentFlat.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viviendas
    {
        public int Cod_casa { get; set; }
        public int Cod_Provincia { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string Ubicacion { get; set; }
        public string Codigo_Posta { get; set; }
        public string Ciudad { get; set; }
        public int Num_habitaciones { get; set; }
        public int Num_banios { get; set; }
        public int Tamanio_vivienda { get; set; }
        public string Descripcion { get; set; }
        public bool Garaje { get; set; }
        public Nullable<int> Cod_TipoVivienda { get; set; }
    }
}
